openapi: 3.0.0
info:
  title: Actian Open Positions API
  description: >
    Actian Careers - Your Take-Home API Project Challenge
  version: 1.0.0
  contact:
    name: HCL Software - Parameswar Mondal
servers:
    - url: http://localhost:3000
      variables: {}
      description: HTTP
tags:
  - name: department
    description: Open Positions
paths:
  /api/open-positions?department={department}:
    get:
      summary: Get open positions by department
      operationId: getDepartmentDetails
      parameters:
        - name: department
          in: query
          description: Department name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenPositionResponse'
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - department
      x-express-middleware:
        - expressRouter:
            expressAppPath: ./app.js
components:
  schemas:
    OpenPositionResponse:
      type: object
      required:
        - result
      properties:
        result:
          type: array
          description: The list of open positions
          example: ['Business Development Representative', 'Sr. Business Analyst']
    ErrorResponse:
      type: object
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          description: The reason for the error
